# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../setup/ox-tmpl/l2.org
#+HTML_LINK_UP: ../index.html
#+TITLE: 粒子物理如何改进你的生活
#+DATE: [2013-07-18 四 21:10]
#+AUTHOR: 译者：心蛛

#+BEGIN_QUOTE
译注：一般人总是以为粒子物理距离我们的生活很远。其实，它离我们真的很近，你会在日
常生活中与它不经意地擦肩而过。

原文: [[http://goo.gl/PZmhu][How particle physics improves your life]]
#+END_QUOTE

* 纸尿裤

#+ATTR_HTML: :width 120px :style float:right
file:application_diapers_0.png

利用粒子加速器，化学家第一次理解了高吸水性聚合物的详细的潮湿结构，这些高吸水性聚
合物就应用在纸尿裤中。这使得他们能够调节和改进高吸水性聚合物的分子式，从而获得更
完美的材料——这已被应用在每个当今的纸尿裤中。

* 热缩包装

#+ATTR_HTML: :width 120px :style float:right
file:application_shrinkwrap_0.png

如果你买了只火鸡，它能够保鲜，这个你得感谢粒子加速器。几十年来，食品产业一直使用
粒子加速器来生产高强度的热缩薄膜，从而让火鸡——也包括水果和蔬菜、烘焙食品、棋盘和
DVD——可以被封装起来。

* 货厢扫描

#+ATTR_HTML: :width 120px :style float:right
file:application_cargo_0.png

每年，美国有超过 20 亿吨货物要通过港口和水路。许多港口如今都采用粒子加速器产生的
高能 X-射线来鉴别违禁品以保障港口安全。这些 X-射线可以穿透很深并能够识别货厢的更
多细节。

* 磁共振成像

#+ATTR_HTML: :width 120px :style float:right
file:application_mri_0.png

这个救命的医疗技术现在称为磁共振成像，它能够对人体的软组织进行详细成像。与 X-射
线不同，磁共振成像能够从大脑的白质中区分出灰质，能从非癌变组织中区分出癌变组织，
能从器官中区分出肌肉，也能够揭露血液流动与中风的征兆。

* 人力开发

#+ATTR_HTML: :width 120px :style float:right
file:application_workforce_0.png

许多经过粒子物理训练的人转行到工业、医药、计算机或其它能够发挥其特长的领域。你会
发现一名粒子探测器专家正在勘探油井，或者一名加速器科学家正在从事癌症治疗的工作。

* 人工心瓣

#+ATTR_HTML: :width 120px :style float:right
file:application_heart_0.png

通过用加速器产生的银离子轰击办法，物理学家设计了一种新材料，它增强了人工心瓣的安
全性。加工后的材料表面能够避免人体将心瓣当作入侵物，从而避免在其周围产生一些有潜
在危险的额外组织。

* 研究用的高强光线

#+ATTR_HTML: :width 120px :style float:right
file:application_light_0.png

环状粒子加速器令高速电子弯曲，导致电子发光。这种光在多种应用中是一种强大的研究工
具。专门的同步辐射加速器也称之为光源，可以让科学家控制光的波长与强度用于研究更好
的电池、绿色能源、新的高性能材料、更有效的药物治疗以及对自然界进行更深入的认识。

* 格点计算

#+ATTR_HTML: :width 120px :style float:right
file:application_grid_0.png

万维网并不是粒子物理对计算领域唯一的促进。为满足 LHC 实验的计算需求，粒子物理学家
创造了世界上最大的格点计算系统，跨越 36 年国家 100 多所研究机构，大大促进了全球网
络和分布计算机的发展。

* 家俱抛光

#+ATTR_HTML: :width 120px :style float:right
file:application_finish_0.png

四分之一个世纪以来，世界上许多公司都在使用粒子加速器产生的电子束来制造防刮、防污
的家俱。这些处理后的凳子、架子和桌子的表面看起来象是木头，但非常耐磨。

