# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../../setup/ox-tmpl/l3.org
#+HTML_LINK_UP: ../../index.html
#+TITLE: “与智慧同在！”
#+DATE: [2013-02-27 三 15:13]
#  - State "DONE"       from "PLANNED"    [2013-02-27 三 15:13]

人们见面或告别，相互之间的问候代表一种文化、民族习惯或时代的特色，或者是一个群体
的共性，或者代表一种美好的愿望。有共同特点的人会自发采用相似的问候语，见面一句话
就能够自然拉近彼此的距离。问候语也是打开话题的良方，促进彼此的交流。

比如中华文化，在许多地方就常常体现在那句经典的问候上：“您吃了没？”饮食男女，勿
须多言。基本上，受过一定教育的人都不再用这样的问候语了。现在，这句问候语也用得比
较少了，随之兴起的问候也五花八门，比如常上微博的人，相互会习惯地问一句：“今天微
博了没？”这也体现了我们时代的变化。

信基督教的人口头语通常有：“赞美主！”、“原主与您同在！”、“阿门！”等等。开讲
之前，佛教徒会来一句：“阿弥陀佛！”或者说“我佛慈悲！”一句问候，一股浓浓的宗教
情绪也随之而来。不得不说，宗教中的问候语有极强的心理暗示作用，即便对不信教的人，
一句“原主保佑你！”大部分人还是乐意听到，尽管，说话的人内心可能正在诅咒你下地狱。

形形色色的问候语中，我最喜欢的是《星际迷航》 (Star Trek) 中瓦肯人 (Valcan) 的问
候语： “[[http://zh.wikipedia.org/wiki/%E7%93%A6%E8%82%AF%E4%B8%BE%E6%89%8B%E7%A4%BC][生生不息，繁荣昌盛]]！ ”英文为 "[[http://en.wikipedia.org/wiki/Vulcan_salute][Live Long and Prosper]]!" 这代表了他们民族
的愿望与目标。每次听到这句问候，总令我心情激动，精神为之一震。下图是瓦肯人问候语
的手势图：
#+CAPTION: 瓦肯的举手礼姿势
#+LABEL: fig:Vulcan-salute-gesture
#+HTML: <a href="http://en.wikipedia.org/wiki/File:Synagoge,_Enschede,_Mozaiek.jpg"><img src="http://goo.gl/NH5sv" style="float:center"></a>

基督教聚会，一句“赞美主”就可以把气氛完全调动起来；一句“阿门”，让教徒散会后仍
有意犹未尽的感觉。《星际迷航》的粉丝聚会，一句 "Live Long and Prosper", 一切尽在
不言中了。

但对于无神论者，对于相信科学的人，我们似乎还没有一句反映大家共性的问候。方舟子的
名言“脑中有科学，心中有道义”，这只是对共性的描述，不适合作为问候语。科学的目的
是为了获得正确的知识与智慧，这智慧表现在我们对形势的把握与决策能力上。智慧可以满
足我们的好奇，便利我们的生活，让生活更美好。尽管宗教也宣称拥有智慧，但那是谎言。
只有科学才能够让人拥有真正的智慧。因此，相信科学，拥有道义的人，我们相互之间不妨
用这样的问候：“ *愿智慧与你同在！* ”或者：
  - *Wisdom be with you!* (英文)
  - *Saĝo estu kun vi!* (世界语)
  - *与智慧同在！*

想象一下，如果我们科学与无神论者聚会时，在开讲与讨论之前，大家共同喊一句：“与智
慧同在！”那会是种什么样的感觉呢？

*愿智慧与你同在！*
