# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../../setup/ox-tmpl/l3.org
#+HTML_LINK_UP: ../../index.html
#+TITLE: 与妻书：《关于生、死与恐惧》
#+DATE:  [2013-03-03 日 13:30]
# - State "DONE"       from ""           [2013-03-03 日 13:30]

老婆：

前日谈起你的担心，因儿子吵闹，话题未能深入。近日，将我的思虑稍作整理，形成文字，
或有助于理解与交流。面谈时或许会而其它干扰，文字也有助于我整理思路。

相识、相爱多年来，你常从梦中惊醒，是因为又梦到年少时的家庭突变。每到此时，除了拥
抱与轻抚，似乎难用言语相慰。所幸这两年来，此梦越来越少，直至绝迹。近来，你似乎又
陷入另一种担忧之中，害怕我突遭变故，你无力独自抚育稚子，然后又噩梦重现。

我前日提到，人们所担心之的危险大致可分三类：第一类是个人几乎无任何力量去改变的事
情，比如飞机失事、地震、战争、致命性疾病、政治运动伤害等；第二类是个人通过努力可
以降低概率的事情，如遵守交通规则降低车祸概率、健康生活方式降低常见疾病的发生概率
等；第三类则是可以避免发生的事情，比如不会游泳前不要让孩子进入深水区。

针对第一类危险，个人既然做不了任何事情去阻止其发生，就尽量采取一些事后补救的措施
了。比如学习一些地震逃生知识、登机时留意一下飞机上的救生常识等。即便是这些事后补
救措施，也未必有效。但这类事情发生的概率极低，绝大部分人一生都可能遇不上，其实担
心与否都无济于事，除了学习常识外，平时根本不用去想。

我们真正需要关心的是第二及第三类事件，我们日常所遇到的大部分危险也是这两类。这两
类事件也稍有区别，那些可通过个人努力来降低概率的事情并不一定就完全不会发生。但这
两类事情有共同点，就是都可以通过学习具体知识与完善个人知识结构来改变——或降低概率，
或阻止发生。而学习具体知识与完善个人知识结构的最主要成果，就是个人的良好习惯。这
些好习惯包括：
  - 遵守交通规则与良好的乘车习惯。比如上车首先系安全带，使用儿童座椅，儿童绝不可
    以坐副驾驶，注意交通灯，公交车上应该抱孩子在胸前，等等。
  - 良好的个人卫生习惯、饮食习惯。比如口腔卫生降低口腔溃疡（也就所谓的“上火”）
    的发生概率；在北京沙尘季节出行带口罩；餐具清洁；等等。
  - 良好的观察或记录习惯，尤其是家中或工作场所的水、电、气等使用的异常。
  - 其它的常识，如雷电期间避免出行，不可用湿手触摸电源开关，电器使用的注意事项，
    节日避免燃放爆竹，等等。

良好的生活习惯，需要家人共同创造。在家中，针对你一些不好的习惯，我偶尔会发点脾气，
希望你能够理解。因为，我觉得，帮助对方养成好习惯，让危险降低到最小，同时让生活很
舒适，这才是爱的最佳表现。而帮助对方做他自己本身应该做的事情，或者事后数落对方的
过失，这些与其说是爱，倒不如说是满足自己的表现。浪漫，应该是生活在安全、舒适基础
上的一种调味品，而不是“必需品”。当生活安全、舒适后，浪漫自然会接踵而至，对吗？

即便是第一、第二类危险，对群体而言，因为科学技术的进步和管理的规范，危险发生的可
预测性也在提高，概率也在降低。举个例子，醉驾对于其他人则属于第一类危险，但随着法
律的强制执行，这类危险概率已经有所下降，这就是管理进步的标志。而 Google 试验的无
人驾驶汽车如果在未来大规模推广开来，机器规避风险能力比人要强，则车祸概率又会进一
步降低，这就是技术进步的好处。

无论是哪一类危险，即便无法阻止其发生，人类目前都有许多积累的事后处理措施，能够让
已经发生的伤害降低到最小。并且，这些措施还会随着科学技术与管理的进步变得越来越完
善。因此，即便有危险发生，也可以降低伤害。

如果你同意我上述所言，那么，不妨一起分析一下你曾经的家庭不幸。因为，我觉得过这么
久，我们又有了孩子，算是重新经历了生，再谈谈死会相对坦然些。

当年，你们一家主要的男性劳力都在矿上为生计奔波。面对未知的矿洞，小叔在不做任何检
测的情况下就率先进入；历经许久未出，于是我未见面的岳父为亲弟弟也进去了，接着就是
三姑父。当你从学校回到家，看到摆在门前的三具遗体时，我能够想象那对你的冲击。当时
尚未成年的你还无法理解这整件事情的含义，但接着寄人篱下的经历，求学与工作后独自的
创荡，这些都变成了那个变故的注脚。多少次从梦中惊醒，你低声诉说起又见到了父亲，每
每令我心碎。我多想有魔法能令他复活，让你从此不再遗憾。但现实是，这绝无可能。

这是一件第三类所忧之事。如果，当时他们能够多了解一些采矿的常识，整个悲剧就可能不
会发生。逝者已去，教训深刻。除了缅怀他们外，我们应该记住教训，多学习常识与具体的
职业知识，养成良好的生活习惯、职业习惯，危险其实会少很多很多。

从怀孕到儿子的出生，再到如今儿子一岁多，我们共同经历了许多：产科病房走道内遛血糖，
胎心监护仪发出的声响似乎还在耳边；手术前夜，好不容易哄你入睡后，我在病房内抄写着
《世界人权宣言》，用笔划来平衡情绪，然后默默安排手术前后即将遇到的每一件事情，包
括为可能的手术意外做好心理准备，所幸一切顺利；深夜赶往医院、彻夜难眠，你在新生儿
病房外含泪地张望；为照顾儿子的肺炎，你从网上寻找教材，学习用听诊器来识别“湿螺
音”；等等。我们经历了生的喜悦，但也同样充满了担忧。当全部的心思都放在孩子身上时，
你的噩梦几乎没有了，你的心态也发生了很大的变化，我明显感觉到你变得更坚强了。是啊，
坚强不是因为没有恐惧，而是因为有了更值得保护的东西。

生与死，一个永恒的话题。生之最大的恐惧之一，就是担心自己或亲人的死亡。因为经历了
死亡，让你产生了噩梦；因为有了更值得保护的人，让你变得坚强；又因为太爱了，以及对
未知的恐惧，让噩梦又复苏了。

可是，老婆，事情不太一样。岳父的意外是可以避免的，尽管很遗憾，但生活还需要继续。
这一点你基本想通了。而担心我发生意外，担心车祸等事情，这样的担心事实上没有必要，
对吗？通过逐渐的交流，你可能已经了解到，我是对规则非常在意的人。我不停地督促你遵
守各种规则，尤其是交通规则、日常电器使用习惯，等等。因为我知道，有许多规则是用生
命换来的教训，尤其是交通规则类似的。我的努力与习惯，实际上会极大降低第二类所忧之
事的概率，基本上会杜绝第三类事件。尽管我的工作场所有一定的危险性，但我经历了充分
的职业安全培训，且每次在实验室我都保持着高度警惕。这样的话，你还担心什么呢？

恐惧是人作为生物体进化而来的一种本能，它的好处是让我们在危险时保持警惕。但过度的
恐惧会让人失去行动能力，反而提高某些不好事情的发生几率。因为不知道坏事什么时候会
发生，或者不知道有哪些可怕的事情会发生，或者不知道坏事发生时如何应对，因此，大部
分的恐惧都是源自未知。可见，消除恐惧的最佳办法，不是逃避或寻找神的寄托，而是尽一
切可能去认识危险，认识得越充分，恐惧就越小，甚至没有。

你曾经问过我：什么是爱情？这真的很难回答。我曾经给出的答案是：爱情，是两个独立人
格之间由性而引发与升华的相互理解、信任、帮助与欣赏。爱情不仅存在于青春的躯体中，
更会存在于与子携老时的将朽之躯。爱情是一个生命的过程，这其中包含有生与死，当然也
包含有恐惧，但更多的应该是共同摆脱恐惧后，对生活的享受。我是那种“理呆”男，不会
什么花样繁多的艺术，不会甜言蜜语。我知道自己唯一擅长的，除了工作赚钱养家外，就是
还有一定的自学能力，在努力把生活必须的种种知识综合起来，督促家人养成好的习惯。对
于家人，我能做的就这么有限。对于你的担忧，甚至恐惧，我觉得前面的分析已经够了，剩
下应该做的是针对每一种可能的危险，我们抽时间来学习与分析。如果，我们这种共同学习
与养成好习惯的过程持续到了彼此的生命终结，这算不算是一种爱情呢？

关于生、死与恐惧，我们需要的是生存的智慧。

愿智慧与我们同在！

老公
2013年03月03日

p.s. 好多个3, 是否暗含着我们的三口之家呢？ :-)
