# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../setup/ox-tmpl/l2.org
#+HTML_LINK_UP: ../index.html
#+TITLE: SCI、EI、ISTP、ISR简介
#+AUTHOR: 心蛛
#+DATE: [2005-05-02 19:09:00]

《SCI》（科学引文索引，Science Citation Index）创刊于1963年，是美国科学情报研究
所（ISI, http://www.isinet.com ）出版的一部世界著名的期刊文献检索工具。 SCI收录
全世界出版的数、理、化、农、林、医、生命科学、天文、地理、环境、材料、工程技术等
自然科学各学科的核心期刊约3500种；扩展版收录期刊 5800余种。ISI通过它严格的选刊标
准和评估程序挑选刊源，而且每年略有增减，从而做到其收录的文献能全面覆盖全世界最重
要、最有影响力的研究成果。所谓最有影响力的研究成果，是指报道这些成果的文献大量地
被其它文献引用。即通过先期的文献被当前文献的引用，来说明文献之间的相关性及先前文
献对当前文献的影响力。这使得SCI不仅作为一部文献检索工具使用，而且成为对科研进行
评价的一种依据。科研机构被SCI收录的论文总量，反映出整个学术团体的研究水平、尤其
是基础研究的水平；个人的论文被SCI收录的数量及被引用次数，反映出个人的研究能力与
学术水平。ISI每年还出版JCR（期刊引用报告， Journal Citation Reports）。JCR对包括
SCI收录的3500种期刊在内的4700种期刊之间的引用和被引用数据进行统计、运算，并针对
每种期刊定义了影响因子（Impact Factor）等指数加以报道。一种期刊的影响因子，指该
刊前二年发表的文献在当年的平均被引用次数。一种刊物的影响因子越高，其刊载的文献被
引用率越高，说明这些文献报道的研究成果影响力大，反映该刊物的学术水平高。论文作者
可根据期刊的影响因子排名决定投稿方向。

《EI》（工程索引，Engineering Index）创刊于1884年，是美国工程信息公司出版的著名
工程技术类综合性检索工具。EI选用世界上工程技术类期刊2000余种。收录文献几乎涉及工
程技术各个领域。例如：动力、电工、电子、自动控制、矿冶、金属工艺、机械制造、土建、
水利等。它具有综合性强、资料来源广、地理覆盖面广、报道量大、报道质量高、权威性强
等特点。

《ISTP》（科技会议录索引，Index to Scientific &Technical Proceedings）创刊于1978
年，由美国科学情报学会编辑出版，会议录收录生命科学、物理与化学科学、农业、生物和
环境科学、工程技术和应用科学等学科，其中工程技术与应用科学类文献约占35%。

《ISR》（科学评论索引，Index to Scientific Reviews）创刊于1974年，由美国科学情报
研究所编辑出版，收录世界各国2700余种科技期刊及300余种专著丛刊中有价值的评述论文。
高质量的评述文章能够提供本学科或某个领域的研究发展概况、研究热点、主攻方向等重要
信息，是极为珍贵的参考资料。

美国科学情报研究所（ISI）还编辑出版以下两种重要的引文工具：
  - 《SSCI》（社会科学引文索引，Social Science Citation Index，
    http://sunweb.isinet.com）为美国科学情报研究所（ISI）建立的综合性社科文献数
    据库，涉及经济、法律、管理、心理学、区域研究、社会学、信息科学等。收录50个语
    种的1700多种重要的国际性期刊，累计约350万条记录。
  - 《AHCI》（艺术人文引文索引，Arts & Humanities Citation Index）为美国科学情报
    研究所（ISI）建立的综合性艺术与人文类文献数据库，包括语言、文学、哲学、亚洲
    研究、历史、艺术等内容。收录1400多种国际权威的期刊，累计200余万条记录。

JCR《期刊引用报告》小资料

JCR《期刊引用报告》由美国ISI出版，全称Journal Citation Reports。JCR对包括SCI收录
的期刊之间引用和被引用数据进行统计、运算，并针对每种期刊定义了影响因子（Impact
Factor）等指数加以报道。期刊的影响因子，指的是该刊前二年发表的文献在当前年的平均
被引用次数。期刊的影响因子越高，也即其刊载的文献被引用率越高，说明这些文献报道的
研究成果影响力大，也反映该刊物的学术水平高。因此，JCR以其大量的期刊统计数据及计
算的影响因子等指数，而成为一种期刊评价工具。

为方便读者查阅和使用，现将JCR中所使用的期刊评价指标的意义和具体算法做简要解释：
1. 总被引频次ct（Cites Total）：指该期刊自创刊以来所登载的全部论文在统计当年被引
   用的总次数。
2. 影响因子imp（impact factor）：影响因子这一评价期刊的重要指标是E.加菲尔德1972
   年提出的，是对一篇文献或文献集合获得客观响应，反映其重要性的宏观度量。通常，
   期刊影响因子越大，它的学术影响力和作用越大。其计算公式为：
   : 影响因子 =（某年引用某刊前两年论文的总次数）/某刊前两年发表的论文总数）
   : 影响因子 = 该刊前两年发表论文在统计当年被引用的总次数/该刊前两年发表论文总数
3. 即年指标imm（immediacy index）：一个表征期刊即时反应速率的指标，主要描述期刊
   当年发表的论文在当年被引用的情况。其计算公式为：
   : 即年指标=该期刊当年发表论文的被引用次数/该期刊当年发表论文总数
4. 被引半衰期hf（cited half-life）：该期刊在统计当年被引用的全部次数中，较新一半
   是在多长一段时间内发表的。被引半衰期是测度期刊老化速度的一种指标。半衰期通常
   不是针对个别文献或某一组文献，而是指某一学科式专业领域的文献总和而言的。
