# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../setup/ox-tmpl/l2.org
#+HTML_LINK_UP: ../index.html
#+TITLE: 超级计算“格点”通过最新测试
#+AUTHOR: 心蛛
#+DATE: [2005-04-30 11:49:00]

原文:  http://physicsweb.org/articles/news/9/4/13

*超级计算“格点”通过最新测试*

2005年4月26日

大型强子对撞机（LHC）于 2007 年在 CERN 投入使用时，它产生的数据量将超有史以来物
理学上的任何一次实验。近日粒子物理学家通过了 LHC 准备中的另一项里程碑式的工作——
连续十天从日内瓦实验室向欧洲和美国的其它七个站点保持了 600 兆字节每秒的不间断的
数据传输流。

在这么多的站点之间维持如此长时间如此高速的数据传输尚属首次。此次挑战中所传输的数
据总量——大约 500 TB ——如果用 512 kb/s 的家用连接带宽来下载将需要 250 年的时间。
此次练习是“服务挑战”四项中的第二项，这些服务挑战将会在数据开始从四个对撞机探测
器（ALICE, ATLAS, CMS 和 LHCb）上流出时进行。

“此项服务挑战是管理来自 LHC 预期的数据洪流的关键一步，” CERN 的服务挑战管理者
Jamie Shiers 说道，“当 LHC 开始运行时，它将会是这个行星上数据最密集的物理设备，
将会在超过十年的时间里每秒产生超过 1500 MB 的数据量。”

CERN 计划使用一个由多个计算中心组成的全球超级计算“格点”（同万维网 WWW 类似，但
更强大）管理来自对撞机的数据，这些数据将由世界各地超过 6000 名的科学家进行分析。

参加最近一次挑战的实验室有：德国 Karlsruhe 研究中心，法国 CCIN2P3 ，意大利的
INFN-CNAF，荷兰的 SARA/NIKHEF，英国的 Rutherford Appleton 实验室，美国的
Brookhaven 和费米实验室。

“这是在计算格点上从未有过的最快的端对端数据传输，”费米超计算工程管理者 Lothar
Bauerdick 这样告诉 PhyicsWeb，“今天的结果表明 LHC 项目是真正的全球合作。但是，
要达到更高的数据传输率，仍然有许多软件和网络研究方面的工作需要做。”

下一次的服务挑战将会在今年夏天进行，将会在连续超过三个月的时间里与更多的计算中心
进行连接。

- 关于作者： Belle Dumé, PhysicsWeb 的科学作家
- /译者/: Exaos Lee, 2005.04.30 
