# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../setup/ox-tmpl/l2.org
#+HTML_LINK_UP: ../index.html
#+TITLE: 发呆综合症，你有吗？
#+AUTHOR: 心蛛
#+DATE: [2005-06-23 13:35:00]

症状：
1. 有很多事情要做，可是做不下去，很烦。
2. 做事情的冲动是常有的，也是常逝的。经常是在吃饭、洗澡、或者和别人闲聊的时候，
   突然产生一种做事情的冲动，然后匆匆赶到办公室或者家里的办公桌前，那种感觉却又
   突然走了，这时你就会坐在办公桌前发呆，或者找其它的事情让自己静下来，比如上网、
   看其它的杂乱东西，比如漫画、小说、电影、flash 等，直到自己静下来能够做事情的
   时候，时间已经过去很多了。如果这时候，有别人要求你替他做事情，你会更烦。
3. 做事情持续的时间不长，经常是不到半个小时，你就会开始不安起来，坐姿变来变去也
   找不到一个适合的，想喝水或者去厕所，却不喝不了多少或者排不出多少。你知道手头
   的事情很急，可是却无法集中精力来完成它，往往这件事情其实只需要你再集中上半个
   或者一个小时就可以做完了，但你总是在这个时候放弃。
4. 为了强迫自己做事情，你定了许多计划，包括什么时间完成什么，甚至每个计划你都加
   上详细的权重和排序因子。什么事情该什么时间做，你很清楚，可是你就是做不下去，
   因此，你的计划总是失败的。
5. 你对许多事情开始失去激情，比如打球、看电影等。你也经常看电影，但那只是你想稳
   定自己的手段，你从电影本身已经找不出多少乐趣了，甚至在看电影或者做其它娱乐的
   时候，你常常走神、发呆。你也会下棋，但走不了几步，你就开始胡乱投子，一局棋往
   往坚持不到结束，你就会投子认输，而其实以你的棋力并不会输掉，你甚至会输给计算
   机。
6. 原来你很乐意助人，但现在你虽然也想去助人，但别人有问题请教的时候，你会觉得比
   较烦，已经不能再象以前那样尽心了。你越来越不乐意和人交流。
7. 你做事情的效率无疑在下降，你越来越着急，可是越着急效率越低，而你越容易发呆。
8. 你最喜欢的事情就是坐在那儿发呆。

还需要我说多少，这些已经是发呆结合症比较严重的表现了，你有吗？ 
