# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../setup/ox-tmpl/l2.org
#+HTML_LINK_UP: ../index.html
#+TITLE: 偷来的与买来的
#+AUTHOR: 心蛛
#+DATE: [2005-06-23 02:05:00]

有一个村子，他们的车基本上都是偷来的：自行车、驴车、骡车、马车、手推车等等。这个
村的村民非常热衷于地下黑车的交易，在村头的大树下或者每周的集市上经常可以见到背上
背着孩子的妇人或者老人，他们冲着经过的村民喊：“要车吗？有新出的车型。”如果有村
民应答了，吆喝的人会带着他们穿过弯曲庄稼地或者柴草堆，然后到一个地下的黑车仓库，
摆出一溜的车子以供挑选。无论市场上卖的价格是 50 万还是 5 千，在这儿只需要 15 或
者更便宜的 5 块就能拿到手。真是卖得高兴，买得舒心。当然，买得也不尽然舒心，主要
是因为偷来的车不能享受诸如售后服务之类的东西，有问题只能自己解决。这样，经过一段
时间的发展，这个村里的玩车高手比比皆是，无论什么样的新车，这儿总能找到高手来搞定。
在这个村里，大家日常饭后的谈资多是那些车子的使用和相互之间的经验交流。

这个村里也会自产一些车，但没有什么大型的豪华车，主要是针对市场上流行的车的修改型，
比如加了个牛角头饰的牛车。即便是这种车，在地下的黑车行里也随时可以很便宜地买到。

车的流行给这个村子带了一种繁荣的景象。村委主任和村支书看到了心里也很高兴。但外村
的人常常说这个村里的人偷车，说得多了，也就不好听了。于是村委提倡自主研发车子，提
倡杜绝偷车的习惯。但用惯了便宜好车的人如何再能够适应昂贵的且并不好用的车？偷车还
是继续，黑车还是流行，但都转到了地下而已，村头卖黑车的妇人带你穿过的草垛更多了几
个罢了。至于自主研发车子？算了吧，研发出来的东西卖不出去，回拢不了资金，那不是浪
费吗？

后来，外面流行一种免费车，车子可以免费使用，可以免费研究所有造车的技术资料。但这
种车却无法在这个缺乏制造精神的村子里流行起来，因为这种车子虽然免费，但那些不免费
的车子已经用习惯了，转开这些车需要的学习代价是很大的，并且地下的黑车还可以继续买
到，何必费那个劲呢？

偷习惯了，就不会自己做了；偷来的车子，也不必太珍惜，反正过不了多久，花上很便宜的
代价又能拿到更新的车型了。你说，这个村里的人是真正懂车爱车的吗？

我说的车，是中国的软件。对于盗版乐此不彼的市场上是无法真正建立地健康的软件行业的，
更无法让开源精神得以广泛的传播。

突然想到以前的一个问题：中国的研究所里有世界上最好的软件，但却很少做出世界上一流
的工作；中国的研究所里使用世界上最新的开发工具软件，但却很少写出世界上非常流行的
代码，到最后还是想方设法去盗国外的软件；在 SourceForge.net 上真正中国人开发并且
非常活跃的软件真是少之又少。也许，这是问题的一个方面。
