# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../setup/ox-tmpl/l2.org
#+HTML_LINK_UP: ../index.html
#+TITLE: AT&T 解散元祖 Unix 部门
#+AUTHOR: 心蛛
#+DATE: [2005-08-17 16:42:00]

UnixReview.com 最近报道美国 AT&T 因内部大幅改组，公司旗下的贝尔实验室在最近被近
解散了发明 Unix 系统的 1127 号部门。该部门自 1969 年至今不断地研究和改进 Unix 系
统，近年广受人们关注的 BSD, Linux, MacOS X 等操作系统的出现与他们的心血是分不开
的。如后是 UnixReview.com 的编辑 Peter H. Salus 所发的公告：
 - http://www.unixreview.com/documents/s=9846/ur0508l/ur0508l.html

#+HTML: <hr />

*1127 部门：再见，再见，永别了！*

作者： Peter H. Salus

1969 年， UNIX 诞生在贝尔实验室。

几十年来，UNIX 的 AT&T 分支的源码都是来自 1127 部门工作者的研究。

当子贝尔实验室从母贝尔实验室脱离时， 1127 部门幸存了。当 AT&T 和 Lucent 分离时，
1127 部门幸存了。

但是贝尔实验的重组最终令 1127 所留下的彻底结束了。我被告之，理论研究者将会去某处，
系统管理者将会去另一处。我不清楚这样的分离将会导致什么样的结局。没有什么恶意，我
仅仅在这儿说说——仅仅是行政上的重组导致目前的裁员和解散使得整个研究领域管理者太多
而研究人员太少。

- Ken Thompson 退休后居于 California.
- Brian Kernighan 目前就任 Princeton 的教授。
- Doug McIlroy 目前就任 Dartmouth 的教授。
- Rob Pike 和 Dave Presotto 及 Sean Dorward 在 Google.
- Tom Duff 目前在 Pixar
- Phil Winterbottom 是 Entrisphere 的 CTO.
- Gerard Holzmann 在 NASA/JPL 实验室做可信赖软件。
- Bob Flandrena 目前在 Morgan Stanley.

就我所知， Dennis Ritchie 和 Howard Trickey 留下，但孤立了。一位前员工在 1127 留
言道：“我认为当 Rob, Presotto 等离开西去 Google 时, 1127 已经差不多快结束了。但
当见到最终的结束时，仍然觉得伤感，既为这个研究所，也为贝尔实验曾经营造的那种研究
氛围的盖棺就寝。”

这可能是糟糕的效果。 DEC 实验解散了。XEROX PARC 于 2002 年一月 4 日莫明变成了
“Palo Alto 研究中心公司”。这是对研究潜力的警示。

再现！再见！伙伴们！“并致谢所有冷血的家伙。” 
