# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../setup/ox-tmpl/l2.org
#+HTML_LINK_UP: ../index.html
#+DATE: [2006-02-20 10:51:00]
#+TITLE: 你所要对抗的不仅仅是 Windows
#+AUTHOR: 心蛛

上周，组内要写一份束流申请表格，我拿到了一份 Word 文档。在 MacOS X 和 Linux 下，
分别用相应的工具打开后，格式基本全乱。有朋友需要申请一个国家自然科学基金，申请书
要求必需使用基金委一个专用的 .exe 格式程序，可是那个程序在模拟的 Windows 环境下
产生了几个用于 M$ Office 的宏和库文件后，我不得不面对无法使用的尴尬。今天，在上
班的路上，想到还没有完成的 Word 文档以及解决这个文档的办法，突然觉得，转到 Linux
之后，我要对抗的不仅仅是 Windows 本身。也许，不管你使用的是不是 Windows 都无所谓，
我们使用 Linux 的人首先要对抗的是那种群体性的习惯。

盗版与 Windows 养成了绝大部分人的计算机使用习惯之后，用一个词，叫做“积重难返”。
在 Windows 下我们养成了许多恶习，主要有：
1. 盗版－－几乎没有几个人会主动去购买必须的软件；有需要的时候，首先想到的是找盗
   版；即使某些特别专业的软件，也会想办法从各种途径去“搞”到，并以能够“搞”到
   为荣；没有几个人知道购买正版软件的途径；甚至于我经常被人问这样的问题：“哪儿
   可以搞到盗版的 Linux ？”问这个问题的人已经不知道什么叫正版，因为在他们的潜意
   识里，我们用的软件默认的就是盗版。
2. 行政的、公开的文档等绝大部分都是 Word 格式，而不管别人是不是能够打开它，因为
   发布这些文档的人默认以为你肯定用的是 M$ Office。可以说，发布这些 Word 文档的
   人肯定没有想过，如果所有的人都去购买正版的 Office，要阅读这些文档需要付出多大
   代价？
3. 默认的文档除了 Word 之外，就是微软的 CHM 格式或者一些专用的格式，诸如超星等，
   而很少有人采用通用于各种系统平台的 ps、PDF、HTML、RTF 等格式来发布文档。而象
   CHM、超星等格式却只有 Windows 版本的阅读工具，这从某种角度上强迫了一些新手用
   户放弃其它的系统平台。
4. 从文档的发布选用特定格式等习惯来看，Windows 的用户很少真正关心阅读其文档的人，
   因为如果你真正希望对方方便阅读你的文档，你就应该考虑到对方能否打开它等问题，
   从另一个方面来看，这是一种霸道：我给你一篇文档，而如果这文档你不得不去阅读、
   编辑与修改的话，你就必须安装和我同样的环境，不管你要付出多大的代价。

群体性的恶力带来的后果也会是灾难性的。Linux 等开源社区是最具有创新精神的，许多新
的东西也都是从这个社区来的，比如 BitTorrent 等 p2p 文件传输模式等。但国人鲜有这
样的创新，因为大家把精力都放到如何破解别人的东西或者如何盗用上了。这种群体性的习
惯也给新东西的传播带来了阻碍。
