# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../setup/ox-tmpl/l1.org
#+HTML_LINK_UP: index.html
#+TITLE: 对青年物理学家的忠告
#+AUTHOR: 作者：波特；译者：何陆
#+DATE: 1958 年第 1 期《原子能科学技术》

#+BEGIN_QUOTE
德国波特教授于 1954 年与麦克思·蓬因发展了测量宇宙线用的符合方法而获得诺贝尔奖金，
于 1957 年 2 月逝世。本文是他在去世前几个星期写的一篇文章，里面有许多切身经验之
谈，虽然他的观点与方法我们不完全同意，但他的经验有些对我们有用处，因此译出来供大
家参考，希望大家用批判的态度对待之。

——译者

（何陆译自德文杂志“Physikalische Blatter”， 1958 年第 1 期）
#+END_QUOTE

* 想法

有些人曾经在一个适当的时机产生了一种想法，从这种想法出发，他建立了他的科学活动生
涯。可是一般的规律却与这不同。在一个人想出的 100 个想法中， 90 个可能证明是无法
实现的，不合时机的，无足轻重的，错误的或者是 诸如此类的。可是在余下的 10 个想法
中，总会有一个想法是最有希望的、最实际的而最容易实现的，需要花时间把它找出来。一
旦找到了这个想法，就要用全力来实现它。

* 简单和灵活性

尽管使用罐头铁皮和封蜡的黄金时代已经过去，还是应该尽量使你的实验装置越简单越灵活
越好。最理想的实验装置应当是在实验的目的达到之后，装置就坏掉了。装置仪器最好从房
间的中央开始。做一个新的实验，首先要把它从头到尾粗略地做一遍。尽管这样会引起许多
麻烦，还是应当把这件事情当作一个规矩来执行。这样做的好处是立刻可以知道各种困难所
在和产生误差的来源。最大的困难常常会出现在完全没有预料到的地方。物理学家也只是人，
不可能一切都预先料到。但是以后每一次的进攻都应当加以考虑。卢瑟福指出过，改变一下
试验方法常常会对我们有帮助。

时常会发现原来的计划和目的无法再坚持下去，在放弃这个试验之前，必需要弄清楚为什么
它行不通，然后也要有勇气来中断它。只要正确地操作，就会使仪器发挥它最好的作用。

即使是可以做下去的实验，由于为了另一个更基本的目的去改变它，还是值得的。主要的问
题是象维恩所说的，当你做实验时，你的眼睛要睁着。为了在需要的时候可以很快地改变实
验方向，实验设备一定要简单明了，而且可以移动。附属的设备，例如复杂的电子学线路等
必须是良好的。附带说一句，不设法修好损坏了的仪器而简单地送还库房是物理学家该死的
罪过。

* 科学工作的经济

每天应该安排一个日程表，常常你会不按照它行事，那么你就应当找出原因（鲍里说过一个
笑话：曾经这样以为过，在德国标准局里，在每天下班的时候，宇宙线就被关掉了。这话有
一点儿道理）。没有日程表，一件工作就会消磨下去而得不到实际的结果。一个日程表会鼓
励人集中自己精力在一个具体的目标上，防止他消耗在枝节的小事情上。物理学家要有一定
程度的休闲，但休闲时亦必须进行思想的活动。

不只一次发生过，从一个不合理的甚至是不正确的叙述开始，得到了意想不到的结果（可以
和一个古老的军事规律来比较，后者大意上说：做错一件事情比什么也不做要好些）。即便
是一个“愚蠢”的实验，如果不太花费时间，也完全可以冒一次险去做一下。要经常去了解
文献，但不要因为自己在无意中重复了别人的工作而感到非常害怕。即使两个工作者做的是
同样的工作，但这还不等于是完全相同，至少各人的产生点是不同的。

* 工作记录本

这也是一个犯不少罪过的地方。应当根本避免将测量结果记在活而本或零散的纸上。如果已
经记地上面了，那么应当立刻将它贴在工作记录本上或者重新抄上去。盖革常常谈起他跟卢
瑟福工作时的一个反面例子，有一次卢瑟福正在读硫化锌上的闪烁计数，他坐在旁边，卢瑟
福要他把读出的数立刻记下来。但不幸的是工作记录不在手边，卢瑟福就对他尖声喊叫“写
在你的袖子上！”

一般来说，应当把所有的东西马上记在工作记录本上，右边记测量的数据，左边记下计算、
实验设备草图、备注和结果。本子上各页要挨次 是第几页，从杯子上撕下纸页，或者将记
有数据的纸扔掉也是该死的罪过。当一个实验必须暂停、中断或者放弃不做时，必须将可以
使人信服应当中断的原因写在本子左边。所有记录本都要妥善地保存好，因为当初有些以为
是错了的东西，可能在过了一些时候甚至许多年以后会发现它是有重要的意义。

* 写文章

写文章要开始得越早越好，最迟当测量完，就马上应当开始，无论如何都不可以等到仪器拆
掉后才开始。在测量完后去休假，过了几个星期或几个月再开始写总结是不好行为，也是组
织工作上的错误。因为第一是记录本上可能有不清楚处，需要在测量的情况情况在脑中记忆
犹新时写总结；第二是人们往往只有到写报告的时候才注意到论证中还有缺陷，而这些缺陷
往往只需要在那原来的仪器装置上再额外地做一点实验就可以解决。稍微夸张一点说，到测
量结束时，你的手稿应该除了还需要填入最后的结果以外，大部分已经写完了。

多考虑一下报告的风格常常是值得的，总的目标应当是简单清楚，句子要短，不要用曲折罗
嗦的句子。首先应当考虑如何明确地叙述你所得到的结果和结论。

写好以后，让这手稿放上一两个星期，然后再用对你的工作只是稍感兴趣而抱怀疑态度的读
者的眼光再来看一遍，于是就可以进行最后的润饰定稿。

一般来说，如果你做工作而不能完全被工作迷住，就最好别做它。每个人必须要认识到不仅
要使自已在工作时间内，而且要在工作时间以外都在酝酿工作中的问题才行。如果做不到这
一点，那么这是一个不好的标志。
