# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../../setup/ox-tmpl/l3.org
#+HTML_LINK_UP: ../../index.html
#+TITLE: 网络上的百科全书、辞典与词典
#+AUTHOR: 心蛛
#+DATE: [2012-05-30 三 10:21]
#+CUSTOM_ID: online-encyclopedia

互联网的特性之一：人人皆可参与。而像百科全书、辞典、词典之类的资料均是靠人海堆出
来的结果。一个人再著作等身，恐怕也很难靠一已之力完成像《大英百科全书》这样的宏篇
巨著。大部分人只专注于一个方向，最多几个方向足矣。因此，在一个人人皆可参与的环境
中汇编百科全书类的资料是最理想的。这儿简单整理一些我现在日常使用或者曾经使用过的
一些网络上的百科类及辞典、词典类资源。

* 百科类网络资源

所谓的百科全书，是对人类现有的全部知识或者某一大类知识进行概要性介绍的工具书，往
往以条目为单元，按辞典形式进行排列。中国的古代有《永乐大典》、《古今图书集成》等，
民国初年有《辞源》、《中国学术百科全书》，现代有《中国大百科全书》。现代的百科全
书纸质媒介的已经逐渐让位于电子媒介。

- 大英百科全书 :: http://www.britannica.com/, 其正式名称为拉丁文 *Encylopædia
                  Britannica* (即 British Encyclopaedia). 第一版于 1768 至 1771
                  于爱丁堡，共三卷；2010 年最后一次印刷版本为 32 卷。2012 年 3
                  月起，大英百科全书公司发表声明不再出版印刷版本，以网络版本为主。

- 维基百科 :: http://www.wikipedia.org, 这个不多解释了。截止此文时，维基百科英文
              共有词条近四百万条。

至于什么“百度百科”类的网络资源基本上就是一批搬运工将维基百科上的内容搬运过去，
并将内容肆意篡改以满足某些人的要求，很难在其中找到公正、真实的资料，建议读者不要
在这些东西上浪费时间。

* 语言类百科，辞典及词典类网络资源

- Omniglot :: http://omniglot.com/, *the online encyclopedia of writing systems
              and languages*, 在线的书写系统及语言百科，它目前包含有 180 种书写
              系统，超过 500 种语言的相关资料， 300 多种人造的书写系统，以及各种
              语言学习的资源。这个网站的作者叫 [[http://omniglot.com/aboutme.htm][葛善明]], 靠这个网站为生。你可以用
              英语、法语、德语、西班牙语、葡萄牙语、世界语、中文等十二种语言给他
              写信。当然，如果他的网站对你有用，最直接的感谢方式还是捐款。 :-)

对于汉语，推荐如下一些网站：
  - 汉典 -- http://www.zdic.net/
  - 中国哲学书电子化计划 -- http://ctext.org/
  - 汉字叔叔的汉字字源网站 -- http://www.chineseetymology.org/

其中关于汉字叔叔的字源网，可参见新闻: [[http://news.xinhuanet.com/world/2011-01/26/c_121026034.htm][把甲骨文搬上网络的美国老头]]。

词典类：
  - 林語堂《當代漢英詞典》 --  [[http://humanum.arts.cuhk.edu.hk/Lexis/Lindict/][网络版]]
  - 韦氏词典网络版 -- http://www.merriam-webster.com/
  - 海词 -- http://dict.cn/

* 学术性的百科

*数学* 类：
  - PlanetMath :: http://planetmath.org/
  - Wolfram MathWorld :: http://mathworld.wolfram.com/
  - Encyclopedia of Mathematics :: http://www.encyclopediaofmath.org

*物理学* 类：
  - Physics Encyclopedia (网络资源) :: http://igorivanov.tripod.com/physics/
  - HyperPhysics (教学) :: http://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html

*化学* 类：
  - IUPAC Gold Book :: http://goldbook.iupac.org/
