# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../../setup/ox-tmpl/l3.org
#+HTML_LINK_UP: ../../index.html
#+TITLE: 强迫症 (OCD) 者的计算机使用表现
#+AUTHOR: 
#+DATE: [2012-04-16 一 09:52]
#+CUSTOM_ID: computer-ocd-users

我简单给出一个列表，讨论一下某类用户使用计算机的表现：
- *对工具本身的关注远远超出对使用工具要完成的目标的关注！*
  - 寻找工具的时间远远超过使用工具的时间。
  - 寻找了许多工具，并进行对比，喜欢 [[http://wikivs.com/][Wiki VS]], 喜欢 Emacs/Vim, Gnome/KDE 等相关的论战。
  - 过度频繁地升级，哪怕根本用不上，也非要先升级上去了才心安。
- *收集资料成癖*, 喜欢把资料分类整理；文件名必须要整齐有序，不停地整理文档
  - 你的硬盘中除电影、音乐之外，是不是有上百 GB 甚至上 TB 量级的各类资料？是不是
    整齐有序？我有，目前办公用机器的种类资料有 600 GB 多，家用机器有 400 GB 多
    (这些不包括电影、音乐等，它们只占很少的一部分), 并且这些文件都整齐有序，我可
    以不用任何搜索工具很快地找到特定的资料。
  - 你是不是特喜欢收集各类软件？不同版本？我有，并且特喜欢收集各类跨平台的软件。
  - 有没有收集源码仓库的癖好？我有，目前收集的有十多 GB 的源码，并且特意编写了管
    理这些源码的脚本程序。
- *停不下来做某件事情*
  - 你有没有每隔几分钟就要到微博、Google Reader、BBS 或者 RSS 阅读器中看一眼？如
    果没看，就觉得心里没着没落的难受？告诉你，我从 2006 年以来，在 Google Reader
    上已经阅读了有 2 万多个条目，其中不包括那些直接点击已读的，而 Google Reader
    算是我登陆比较少网络服务之一。至于微博、BBS、论坛，每天都要耗掉大量的时间，几
    乎每隔几分钟就要去查看一次的那种。
  - 使用 ArchLinux, 每隔几个小时，都要执行一次 =pacman -Syu=! 如果出差或者其它原
    因未能执行这个命令，心中会感到抑郁，感觉少了些什么。
- 离开计算机就会出现沮丧、恐惧、焦虑、紧张、易激动等情绪？我有！
- 离开计算机，注意力无法集中于某些事情，比如读书、欣赏花草、郊游等？我有！
- 总觉得自己的计算机不够用，它的功能不够强大？总希望购买更新更快的配件？我有！
- 看到别人的计算机装满 360 之类的流氓软件会心理难受？我有！
- 觉得别人使用计算机的某些习惯特蠢会心理难受？我有！
- 忍不住想教别人如何更快捷地使用计算机？我有时会忍不住。 =:-(=

好了，不用再罗列了！我想，上述的这些表现如果都有的话，不得不说: \\ 
*恭喜！你是个使用计算机的强迫症者！*

[[http://en.wikipedia.org/wiki/OCD][强迫症]] 是焦虑症的一类，其特点是如果不重复做某些事情，就会出现不安、恐惧、担忧等情
绪，也只有通过重复做某类事情才能够缓解。强迫症是美国第四大常见的精神失调，它与哮
喘、糖尿病一样常见（注意，强迫症与 [[http://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_personality_disorder][强迫性人格]] 并不一样）。根据相关资料，强迫症者
多拥有较强的联想和想象力，智商一般也高于常人，但长期缺乏安全感，对某些方面的担忧
持续存在，对现实的感知力有所下降等，会导致类似的后果。另外，体内的血清素、多巴胺
的不平衡、环境因素等也可能是诱因。对于强迫症的病因，还有其它的说法。但一般认为，
对病情较轻的使用解释性的心理治疗和药物辅助即可，还有就是 [[http://en.wikipedia.org/wiki/Morita_therapy][森田疗法]]。

对于计算机使用中的强迫症，似乎顺其自然也无不可。但有些时候这种状态会影响现实生活
中的其它方面，比如家庭氛围、工作计划等，甚至对用户的生理健康也造成一定的影响。因
此，不妨读一读森田疗法，自行做一点改变。但我更乐意推荐的是使用 [[http://en.wikipedia.org/wiki/Getting_Things_Done][GTD]] 和 [[http://en.wikipedia.org/wiki/Pomodoro_Technique][番茄工作法]]
来管理你的日常生活。当然，请不要在收集一大堆的这类资料后，把方法本身都忘记喽！既
然可以强迫着去做其它事情，不妨真正强迫自己一回，把这两种方法应用起来！
