# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../setup/ox-tmpl/l1.org
#+HTML_LINK_UP: index.html
#+TITLE: 怎样成为一名优秀的理论物理学家 
#+AUTHOR: Gerard't Hooft, 译：心蛛

#+BEGIN_QUOTE
Gerard't Hooft，这位 [[http://nobelprize.org/physics/laureates/1999/index.html][1999 年诺贝尔物理学奖获得者]] (与 Martinus J. G. Veltman 共享)
的 [[http://www.phys.uu.nl/~thooft/][个人网站]] 上有许多很启发的东西，其中一篇文章让我很受益，即 "[[http://www.phys.uu.nl/~thooft/theorist.html][How to become a
good theoretical physicist]]". 马红孺教授已经在他的个人网站上已经给出了一个译文。
我再译一遍，算再加深一次理解吧。

参考：
- Gerard't Hooft 的个人网站: http://www.phys.uu.nl/~thooft/
- 文章原文: http://www.phys.uu.nl/~thooft/theorist.html

更新记录:
  - 2013-07-19: 这是 [2004-10-20 05:45:00] 我发布在 LiveJournal 上的译文。原文已
    经于 2009 年更新过。
#+END_QUOTE

#+HTML: <hr />

#+BEGIN_QUOTE
此网站（仍在建设中，才刚刚起步）是为年轻的学生——和所有（象我一样）为真正的科学所
带来的挑战而激动不已的人，以及那些象我一样决心用他们的大脑来发现我们所生存的真实
世界中的新事物的人——所准备的。简而言之，此网站是为那些决定将其时间投入理论物理的
人而准备。
#+END_QUOTE

我常常收到这样的来信——本意甚好但毫无用处——是那些业余物理学家写来的，他们相信自己
解决了世界难题。他们之所以相信自己仅仅是因为他们根本没有弄明白现代物理中解决问题
的真正方法。如果你真的想为物理规律的理论解释作出贡献（如果你成功了，那的确是非常
激动人心的事！）你就需要懂得许多东西。首先，要严肃对待。大学里教授了所有必需的科
学课程，自然，你首先应该做的就是进入一所大学并尽你所能吸收一切知识。但如果你还很
年轻，仍然在中小学阶段，仍然在忍受那些为孩子准备的称之为科学的传奇故事，你会怎么
做？如果你已经年纪较长，再也不愿意加入那些吵闹不休的 年轻学生之中，你又会怎么做
呢？

如今，从互联网上搜集你所需要的一切知识已经成为可能。问题是，网上的垃圾非常多。会
不会漏掉那些少得可怜的而对你真正有用的页面呢？我非常清楚需要教哪些东西给刚入门的
学生。列出那些绝对必需的课程名称与专题是很容易的，我已经在后面列出了。我的目的是
在网上找到那些真正有用的文章和书籍，最好是能够下载的。这样说来，成为一名理论物理
学家的成本不会超过一台能接入互联网的计算机、一台打印机、大量的纸张和笔。不幸的是，
我还不得不建议你去购买课本，但很难在这里给出建议；或许将来的网站上会有。让我们首
先实现最低限度的需要。后面列出的科目是必须要学习的。任何的疏漏都将得到惩罚：失败。
相信我吧：你不要读到后就相信它——应该检验它。你可以尝试其它的途径，尽你的所能去试。
你会一再惊讶地发现，那些家伙所做的已经是最聪明的了。最好的课本都有练习。做做这些
练习，看看你能否全部理解。尽量达到这种程度：你能发现大量的印刷错误，微小的错误，
直到更重要的错误，设想你会有更好的方式来写这些教材。

我可以告诉你一些自己的经验。我非常幸运的是周围有许多非常棒的老师，这一点帮助了我
防止误入歧途，直到我获得诺贝尔奖。但我没有互联网。我要努力成为你们的老师，这是件
非常艰巨的任务。我正请求学生、同事及教师来帮助我完善这个站点。此站点目前仅仅是为
那些希望成为理论物理学家的人——不是普通的那些人，而是那些非常棒的、下定决心去获得
自己的诺贝尔奖的人——而设立的。如果你非常谦虚，那么，首先上完那些糟糕的学校，然后
按部就班跟着那些学者和专家们，等他们把那些一小部分知识反复无聊地嚼烂之后再交给你
们。这个站点是为那些有雄心壮志的人准备的。我相信任何人都能做到，只要他具备足够的
知识、兴趣和决心。

理论物理好比一座摩天大厦，它最基础的部分就是基础数学和经典的（20世纪之前的）物理
学内容。不要认为因为我们已经懂得很多，从而20世纪之前的物理学就是无关紧要的了。在
那些日子里，有了这些坚实的基础才有了我们现在享用的知识。在你没有亲自建好地基之前，
不要妄想去建立你的摩天大厦。我们摩天大厦的最初几层是由高等数学公式构成，它们是由
经典物理学理论变成的漂亮公式。如果你想更进一层，它们是必须要走的。接着，就是后面
所列的许多课题。最终，如果你足够疯狂，你希望解决那些量子世界里的 Reconciling
Gravitational 物理中异常繁难的问题，你就需要学习广义相对论、超弦理论、M-理论、
Calabi-Yau compactification ，等等。这是目前摩天大厦的顶端。还有一些其它的顶端，
比如玻色－爱因斯坦凝聚、分数量子霍尔效应等等。根据过去这些年的证明，这些也同时是
非常好的诺贝尔奖级别的课题。给你一个忠告：即使你非常聪明，你仍然会在某处陷入困境。
自己在网上冲浪吧，尽情找吧。告诉我你发现了什么。如果此站点帮助了某些正准备进入大
学学习的人，或者激励了某些人，或者替某些人引了路，帮助他或她在科学的道路上走得更
顺当，那些，我认为此站点是成功的。请回馈给我。这儿有一个列表。

*课程列表，按逻辑顺序* （并非所有内容都一定要按照此表列来进行，但此列表大概说明
了这些不同课程之间的逻辑关系。某些注释比其它的要高一层次）

以 .ps 结尾的文件是 PostScript 文件，可以用 gsview 程序打开它们。

（尚在起步阶段，此页面的内容仍然非常不完善！）


*语言*: 英语是一个先决条件。如果你还没有掌握它，下功夫学吧。你必须能够读、写、说
及理解英语，但不必要达到最好。这篇文章的糟糕英文是我写的，这已经足够了（译注：这
是作者的谦虚之词）。所有出版物都是英语的。注意能够用英语写作的重要性。迟早，你将
希望发表自己的结果，而人们必须能够读懂并理解你的内容。

法语、德语、西班牙语和意大利语或许有用，但他们不是必须的。它们不是摩天大厦的地基，
所以不必要担心。你的确需要希腊字母。希腊字母用得非常多。学会它们的名字，否则当你
口头表达时会把自己弄糊涂。现在开始点严肃的内容。不要抱怨这些东西看起来很多。诺贝
尔奖不是靠吹灰之力就能获得的，并且要记住，所有这些东西加起来至少需要我们学生五年
的强化学习（至少有位读者对此很惊讶，他/她认为自己在五年时绝对不可能全部掌握；事
实上，我是就那些计划花费其大部分时间用于这些学习的人而言的，并且还需要有一些基本
的智力。

*基础数学*: 你熟悉数字、加法、减法、平方根等等内容吗？
  - 自然数：1, 2, 3, ...
  - 整数： ..., -3, -2, -1, 0, 1, 2, ...
  - 有理数（分数）： ... .., 23791/773, ...
  - 实数： Sqrt(2)=1.4142135..., π=3.14159265..., ε=2.7182818...
  - 复数： 2+3i, eia=cosa + i sina, ... 他们非常重要！
  - 集合论：开集， 紧致空间， 拓扑 \\
    你或许会惊讶，他们在物理中的确很有用！ \\
    ［旁注：在 [[http://www.gotmath.com/notes.html][这儿]] 寻找更多的网上课程！（比你所需要的更多） ］
  - 代数方程。近似处理。级数展开：泰勒级数。解带复数的方程。三角函数： sin(2x) = 2
    sin(x) cos(x) ，等等。
  - 无穷小量。微分。基本函数（sin, cos, exp）的微分。积分。可能的话，基本函数的
    积分。微分方程组。线性方程组。傅立叶（Fourier）变换。复数的使用。级数收敛。
  - 复平面。柯西（Cauchy）定理和路径积分（这个现在很有意思）。Gamma 函数（学习它
    们的特性是种享受）。高斯（Gaussian）积分。概率论。
  - 偏微分方程。狄里克雷（Dirichlet）和纽曼（Neumann）边界条件。

［旁注：Dave E. Joyce 的三角函数课程这是必须的内容，James Binney 教授的复数课程
上面的内容这儿（差不多）全有！（K. Kubota, Kentucky）。同时参考 Chris Pope 的课
堂笔记：Methods1-ch1, Methods1-ch2复平面、柯西定理和路径积分（G. Cain, Altanta）］

这些是针对初学者的。某些专题是实际是作为整个课程来学习的。这些内容的大部分是物理
理论的非常重要的组成。你没有必要先要学习完全部内容才开始后续课程，但要记住要回来
完成那些第一轮学习时漏掉的内容。

*经典力学*: 静力学（力，张量）；流体力学。牛顿定律。行星的椭圆轨道。多体系统。作
用量原理。哈密顿（Hamilton）方程。拉格朗日量（千万别跳过——非常重要！）。谐振子。
摆。泊松（Poisson）括号。波动方程。液体和气体。粘滞性。纳维－斯托克斯
（Navier-Stokes）方程。粘滞力与摩擦力。

［旁注：一组来自哈佛的很棒的笔记关于拉格朗日量和哈密顿方程的更多资料］

*光学*: 折射和反射。透镜和镜子。望远镜和显微镜。波传导概论。多普勒（Doppler）效
应。波叠加的惠更斯（Huijgen）原理。波前（Wave fronts）。焦散线（Caustics）。

［旁注：A. A. Louro 的光学课堂笔记］

*统计力学和热力学*: 热力学第一、第二和第三定律。玻尔兹曼（Boltzmann）分布。卡诺
（Carnot）循环。熵。热机。相变。热力学模型。伊辛（Ising）模型（推导到求解二维及
以上的伊辛模型）。

［旁注： Alfred Huan 的统计力学教程］

普朗克（Planck）辐射定律（量子力学的前奏）。

［旁注： Donald B. Melrose 教授的热动力学讲座笔记］

（仅仅需要一些非常基本的内容）电子学：电路。欧姆定律，电容，电感，使用复数计算它
们的效应。晶体管，二极管（以后再讨论它们的工作原理）。

甚至最纯粹的理论家他也会对计算物理的某些方面感兴趣。

［旁注：James Kelly Angus, 针对理科学生的 Mathematica MacKinnon, 计算物理］

*电磁学的麦克斯韦（Maxwell）理论*: 麦克斯韦定律（同质和异质）

介质中的麦克斯韦定律。边界条件。求解如下情况的方程：真空和单一介质（电磁波）；腔
中（波导）；边界处（折射和反射）

［旁注：W. J. Spence, 电磁学 Bo Thide 的电磁场理论课本（高等）Jackson 的课本中习
题解：第1部分 / 第2部分 ］

(非相对论) *量子力学*: 坡尔（Bohr）原子。德布罗意（De Broglie）关系（能量－频率，
动量－波数）。薛定鄂（Shrödinger）方程（包括电势和磁场）。艾伦菲斯特（Ehrenfest）
定理。箱中的单粒子。氢原子，详细的求解。塞曼（Zeeman）效应。斯塔克（Stark）效应。
量子谐振子。算符：能量，动量，角动量，产生和湮灭算符。算符间的对易规则。量子力学
散射理论导论。S矩阵。放射性衰变。

［旁注：量子力学和狭义相对论导论，Michael Fowler另一个导论Niels Walet 的量子力学
讲座（Manchester），笔记］

*原子和分子*: 化学键。轨道。原子和分子光谱。光的发射和吸收。量子选择规则。磁动量。

*凝聚态物理*: 晶体。布拉格（Bragg）反射。晶簇（Crystal groups）。介电和抗磁常数。
布洛赫（Bloch）谱。费米（Fermi）能级。导体，半导体和绝缘体。比热。电子和空穴。晶
体管。超导。霍尔（Hall）效应。

［旁注： Chetan Nayak 的凝聚态物理笔记（UCLA）］

*等离子体物理*: 磁流体动力学。阿尔文（Alfvén）波。

*高等数学*: 群论，及群的线性表示。李（Lie）群论。矢量和张量。更多求解（偏）微分
方程和积分方程的方法。极值原理和基于此原理的近似处理方法。差分方程。产生函数。希
尔伯特空间。

［旁注：参见 John Heinbockel, Virgunia; 参见 Shr. Pope：Methods2 ］

泛函积分导论。

［旁注：G. 't Hooft: 李群，（教材为丹麦语）包括练习; 特殊函数和多项式（你没有必
要记住，理解其原理即可）］

*狭义相对论*: 洛伦兹（Lorentz）变换。洛伦兹收缩，时间膨胀。 E=mc2 。四维矢量和四
维张量。麦克斯韦方程的变换规则。相对论多普勒效应。

［旁注：Peter Dunsby 的张量和狭义相对论讲座 ］

*高等量子力学*: 希尔伯特空间。原子跃迁。光的发射和吸收。受激发射。密度矩阵。量子
解释。贝尔（Bell）不等式。相对论量子力学方向：狄拉克（Dirac）方程，精细结构。电
子和正电子。超导的 BCS 理论。量子霍尔效应。高等散射理论。色散理论。微扰展开。WKB
近似，极值原理。玻色－爱因斯坦凝聚。超流体氦。

［旁注： Michigan 的量子力学（高等）笔记］

更多的 *唯象理论*: 亚原子粒子（介子，重子，光子，轻子，夸克）和宇宙射线；材料性
质和化学；核的同位素；相变；天体物理（行星系，恒星，星系，红移，超新星）；宇宙学
（宇宙模型，膨胀宇宙学说，微波背景辐射）；探测技术。

*广义相对论*: 度规张量。时空曲率。爱因斯坦的引力方程。施瓦茨查尔德
（Schwarzschild）黑洞；李斯纳－挠茨陶姆（Reissner-Nordström）黑洞。近日点移动。
引力透镜。宇宙模型。引力辐射。

［旁注：G. 't Hooft 的导论和练习; 其它的： Sean M. Carrol 的广义相对论讲座笔记］

*量子场论*: 经典场论：标量场，狄拉克－旋量场，杨－密斯（Yang-Mills）矢量场。

相互作用，微扰展开。自发对称破缺，戈德斯通（Goldstone）模式，黑格斯（Higgs）机制。

粒子和场：福克（Fock）空间。反粒子。费曼（Feynman）规则。π介子和核的盖尔曼－列
维（Gell-Mann-Lévy）Σ模型。圈图。么正性，因果性和色散关系。重整化（泡利－维拉
斯，Pauli-Villars；维数重整化）。量子规范理论：规范固定，法捷也夫－波波夫
（Faddeev-Popov）行列式，斯拉夫诺夫（Slavnov）恒等式，BRST对称。重整化群。渐近自
由。

［旁注： Pierre van Baal 的量子场论笔记］

孤立子，Skyrmions。磁单极和瞬子（instanton）。夸克禁闭机制。1/N 展开。算符乘积展
开。贝塔－萨佩塔（Bethe-Salpeter）方程。标准模型的建立。 P 和 CP 破缺。 CPT 定理。
自旋和统计关联。超对称。

*超弦理论*

［旁注：导论和练习; 关于超弦的非专业站点］

可以到这儿找更多的教程笔记。

书籍。在理论物理各个专题都有很多的好书。

这儿列出几本：

- H. Margenau and G.M. Murphy, The Mathematics of Physics and Chemistry, D. v.Nostrand Comp.
- R. Baker, Linear Algebra, Rinton Press

- L. E. Reichl: A Modern Course in Statistical Physics, 2nd ed.
- R. K. Pathria: Statistical Mechanics
- M. Plischke & B. Bergesen: Equilibrium Statistical Physics
- L. D. Landau & E. M. Lifshitz: Statistical Physics, Part 1
- S.-K. Ma, Statistical Mechanics, World Scientific

- J.D. Jackson, Classical Electrodynamics, 3rd ed., Wiley & Sons.

- A. Das & A.C. Melissinos, Quantum mechanics, Gordon & Breach
- A.S. Davydov, Quantum Mechanics. Pergamon Press
- E. Merzbacher, Quantum Mechanics, Wiley & Sons
- R. Shankar, Principles of Quantum Mechanics, Plenum
- J.J. Sakurai, Advanced Quantum Mechanics, Addison-Wesley

- B. de Wit & J. Smith, Field Theory in Particle Physics, North-Holland
- I.J.R. Aitchison & A.J.G. Hey, Gauge Theories in Particles Physics, Adam Hilger
- L.H. Ryder, Quantum Field Theory, Cambridge Univ. Press
- C. Itzykson & J.-B. Zuber, Quantum Field Theory, McGraw-Hill.

- M.B. Green, J.H. Schwarz & E. Witten, Superstring theory, Vols. I & II, Cambridge Univ. Press
- J. Polchinski, String Theory, Vols. I & II, Cambridge Univ. Press

到这儿找找其它有用的课本：数学，物理（这些东西许多是为了消遣而不是认识世界）

已经有了一些回应。我感谢这些人：Rob van Linden, Robert Tough, Thuy Nguyen, Tina
Witham, Jerry Blair, Jonathan Martin 。

最后更新：2003 年二月20日

译注：翻译时间 2004.10.18-19 
