# -*- mode: org; coding: utf-8; -*-
#+SETUPFILE: ../../../../setup/ox-tmpl/l3.org
#+HTML_LINK_UP: ../../index.html
#+TITLE: 做快乐的无神论者
#+AUTHOR: 心蛛
#+DATE: [2013-07-10 三]

#+BEGIN_QUOTE
注：本文同时发表在 [[http://www.scipark.net/2013/07/%E5%81%9A%E5%BF%AB%E4%B9%90%E7%9A%84%E6%97%A0%E7%A5%9E%E8%AE%BA%E8%80%85/][科学公园]]。
#+END_QUOTE

“人为什么活着？”自第一次在日记中写下这个问题至今，二十多年来，我曾有过许多种答
案，但说不上哪个最透彻、最准确。其实，这样的问题没有所谓的“标准答案”。在他人与
自己的那些形形色色的答案中，我想，有一个比较通俗且容易被接受，那就是——为了快乐。
那么，什么是快乐？为了阐述清晰，不妨把来自生理上的愉悦感觉称之为快感，来自心理上
的愉悦感觉称之为快乐。而来自心理上的愉悦是一种很主观的感受，其近义词有很多，比如
幸福。这样，如果把快乐作为人生的目标，或者说，人活着是为了幸福，这个目标就显得主
观了。那么，快乐地活着，有没有什么客观的尺度可以来衡量呢？

什么是客观？自然是指外在的能够被许多人感知到的那些实实在在的东西。对于这些客观的
东西，如果认为它们是由某种超自然的神力所创造，并且认为这种神力还在持续影响着周围
的世界，甚至包括人的主观感受，持这种观念的人则是有神论者。而如果认为这些客观的东
西非神力所造，只是按其固有的规律在持续演化着，人们只能靠适应这些规律来生活，持此
观点的则可视为无神论者。有一类人会认为世界最初是由一种神力所创，但认为神力只是在
创世那一刻起作用，以后则不再影响其所创造的世界，世界本身只按其设定的规律在运行，
持此观点的可视为弱无神论者。无论对最初神力存在与否持什么观点，只要认为我们所处的
世界现在与未来只受其固有规律的支配，不再受任何神力的影响，则就是无神论者。无神论
者的世界是客观的，它不会因任何主观的神力而改变，只受其固有的规律影响。

那么，什么是客观的快乐呢？通过观察会发现，那些人们会表现出快乐情绪的事情通常会满
足了其生理或心理需求。不管人们的需求能否按马斯洛的理论层次来排序，简而言之，快乐
是人们在需求被满足后的一种情绪。而现代生物学还告诉我们，快乐的情绪有其客观的生理
基础，那就是大脑内神经传递质的作用，“快乐就在大脑中”。

如何追求快乐？有神论者与无神论者在此产生了分野。由于相信外来的神力会改变世界，有
神论者会把希望寄托于此，而且他们坚信能够招来这种神力的只有虔诚的信仰或某些宗教行
为，比如冥想、祈祷、祭祀、奇怪的仪式等等。无神论者，包括弱无神论者，则把希望寄托
在自身，希望通过认识与理解自然界的规律，通过改变自身的行为适应外界的规律，以满足
需求，从而快乐。

人们的需求可简单分为生理的与心理的。在物质条件足够的情况下，除了性之外的生理需求
基本上都能满足，都能够带来快感。对于性，则偏重于心理层面更多些，要有合适的人与合
适的条件，也就是常说的爱情。心理上的需求虽然更为复杂，也可简单划分为社交性的与求
知性的，其中求知性的需求亦即人们对未知的好奇心。马斯洛的需求层次论中较高级的需求
包括——爱与隶属需求、尊严需求、自我实现需求，这些需求基本上都属于社交性的需求。

有神论者通常也是宗教徒，他们经常从事的活动有祭祀与各种宗教仪式，而这些活动本身往
往也是社交行为，某种程度上满足了人们的社交需求。因此，某些研究宗教的文献得出了这
样的观点，即“宗教让人心理强大”、“宗教让人不寂寞”等，也就不奇怪了。而对于求知
性需求的满足所带来的快乐，我猜测，由于这方面的研究难度相对较大，不容易建立客观的
衡量标准，故未曾读到相关的文献。有神论者，除了参加宗教活动所获得的社交性的满足外，
他们追求快乐的其它手段，诸如祈祷、冥想等，不过是一种自我逃避与麻痹。

作为无神论者，我们不相信神力，我们满足自己的需求则需要首先依靠科学方法来认识世界、
认识规律，然后再调整自身的行为来适应世界。而使用科学方法认识世界的过程本身，则满
足了我们的求知性的需求，即我们的好奇心。世界如此之大，任何一个方面深入下去，都可
以源源不断地挖掘出新鲜的东西出来，因此，我们的好奇心会不断被挑起，又不断被满足，
快乐无边。而我们对世界认识得越透彻，规律理解得越准确，调整自身的行为就越有把握，
也越有效率，对基本生理层次需求的满足也越便利：比如对于最基本的饮食需求，一百年前
贫瘠的土地能够养活的人口极其有限，而利用现代农业培育技术与转基因技术，不仅农作物
的产量足够养活 70 亿人口，而且食物的种类也远远比以前丰富。土摩托在一篇日记中曾经
提到幸福的两个客观标准，一个是可选择，一个是可持续。而无神论者需要充分认识世界才
能够调整自己适应世界，认识充分，选择自然也多，也容易找到可持续的快乐。无神论者对
快乐的追求，有着坚实的基础，那就是知识与智慧。

社交性的需求属于人们的基本需求。而现阶段，崇尚科学的无神论者在数量上偏少，寻找到
志同道合者并进行频繁交往的则更少。因此，无神论者应该多一些聚会，多一些交流，可以
先形成某种较固定的聚会形式，形成无神论者社交的一个核心。这样，宗教徒因聚会与仪式
所带来的社交快乐，对于无神论者而言，也不再缺乏。

由于历史的原因，宗教在目前这个星球上仍然占据着主流，某些类似于宗教的愚昧思想，比
如中医等，仍然在生活中变换着奇怪的颜色。因此，在现阶段，做一名无神论者，更加需要
知识、智慧，而且公开的无神论者还需要勇气。但不管现阶段如何，只有坚持科学认知方法
的无神论者才会找到真正可持续的快乐。

做快乐的无神论者！
